### ISSUE TITLE
admin账号无法登录，看数据库没有admin这个用户？

### ISSUE THREAD

**Issue by huxxhua** [v-mars/jobor#5]
登录提示:`[ERROR] 2021-08-19 17:58:10 - [admin]认证失败，用户名或密码不对,请重新输入！`
 - 版本Version [2.0/.2]
 - OS [Mac]

**Comment by laixiaohuai** [comment]
用的啥用户名密码

**Comment by ci666** [comment]
@laixiaohuai 登录后台的时候的提示
![image](https://user-images.githubusercontent.com/20944512/130071197-72bc6855-01fe-4129-9c05-029f83fb9b2b.png)

**Comment by laixiaohuai** [comment]
> @laixiaohuai admin/admin 是数据库user表没数据的原因？

我应该是初始化有默认的用户的，你可以清空表，重启服务，会重新初始化数据库的

**Comment by ci666** [comment]
删除表了，启动报错了，但是二次启动server会成功，会不会由于第一次启动异常，数据没写入到数据?
![image](https://user-images.githubusercontent.com/20944512/130173522-7f668cf2-4944-4b70-b8ad-82c51774bb4e.png)

**Comment by laixiaohuai** [comment]
我微信：boen1990有什么问题可以直接找我微信沟通




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [v-mars/jobor] admin账号无法登录，看数据库没有admin这个用户？ (#5)





 
删除表了，启动报错了，但是二次启动server会成功，会不会由于第一次启动异常，数据没写入到数据?
 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
